name: Terraform CI

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2

      - name: Run Terraform checks
        run: |
          for dir in Assign1 day2 day4 bonus; do
            echo "Checking $dir"
            cd $dir

            terraform init -backend=false

            terraform fmt -check || true
            terraform validate || true
            terraform plan || true

            cd ..
          done
